namespace: s3pweb
name: redis
version: 1.0.0
readme: README.md
authors:
- JB Rabin <jean-baptiste.rabin@s3pweb.com>
description: redis ansible role
license:
  - GPL-2.0-or-later
tags:
  - redis
dependencies: {}
repository: https://github.com/s3pweb/ansible-redis
documentation: ''
homepage: ''
issues: 'https://github.com/s3pweb/ansible-redis/issues'
build_ignore: []

